version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: scripts/install_httpd.sh
      timeout: 60
      runas: root
  # ValidateService:
  #   - location: scripts/MonitorService.sh
  #     timeout: 3600
  #     runas: root
